name: Nanoc

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["2.7", "3.0", "3.1", "3.2.", "3.3"]

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: bundler-b-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('Gemfile') }}

      - run: |
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs "$(nproc)"

      - name: Test style
        if: ${{ matrix.ruby-version == '3.3' }}
        run: bundle exec rake rubocop

      - name: Test nanoc-core
        run: bundle exec rake nanoc_core:test
        timeout-minutes: 3

      - name: Test nanoc
        run: bundle exec rake nanoc:test
        timeout-minutes: 3

      - name: Test nanoc-cli
        run: bundle exec rake nanoc_cli:test
        timeout-minutes: 3

      - name: Test nanoc-checking
        run: bundle exec rake nanoc_checking:test
        timeout-minutes: 3

      - name: Test nanoc-dart-sass
        run: bundle exec rake nanoc_dart_sass:test
        timeout-minutes: 3

      - name: Test nanoc-deploying
        run: bundle exec rake nanoc_deploying:test
        timeout-minutes: 3

      - name: Test nanoc-external
        run: bundle exec rake nanoc_external:test
        timeout-minutes: 3

      - name: Test nanoc-live
        run: bundle exec rake nanoc_live:test
        timeout-minutes: 3

      - name: Test nanoc-tilt
        run: bundle exec rake nanoc_tilt:test
        timeout-minutes: 3

      - name: Test nanoc-spec
        run: bundle exec rake nanoc_spec:test
        timeout-minutes: 3

      - name: Test guard-nanoc
        run: bundle exec rake guard_nanoc:test
        timeout-minutes: 3
